### PR TITLE
WREN

### PR DESCRIPTION
**Pull request by luc4s**
This PR is a base branch for modifications specifically related to WREN, which shall be merged when WREN is merged into develop.

### CODE REVIEW

**Comment by DavidMansolino** [comment]
The camera.compositor field has to be updated.

**Comment by DavidMansolino** [comment]
`ShaderPart` and `Uniform` nodes has to be removed (no need to update the node_hierarchy image, it will be updated in #670).

**Comment by DavidMansolino** [comment]
Same for `ComposedCubeMapTexture`, `ComposedShader`  and `MultiTexture`

**Comment by tn12787** [comment]
👍

These changes should bring the doc in line with the changes to nodes on the WREN branch.

**Comment by DavidMansolino** [comment]
👍

**Comment by tn12787** [comment]
👍

**Pull request merged**
