### PR TITLE
Feature OSM filter multipolygon buildings

### PR DESCRIPTION
**Pull request by DavidMansolino**
Linked to omichel/webots#3980

### CODE REVIEW

**Comment by DavidMansolino** [comment]
:+1:

**Comment by omichel** [comment]
:+1:

**Comment by omichel** [comment]
:+1:

**Comment by omichel** [comment]
There is a mismatch between this documentation and the help displayed by importer.py: the names of the objects are plural in importer.py whereas they are singular in the documentation. The plural form looks better to me...

**Comment by DavidMansolino** [comment]
Ok, I will use the plural form everywhere.

**Comment by DavidMansolino** [comment]
@omichel would you rename the option too `--noBuilding` => `--noBuildings` ?

**Comment by omichel** [comment]
Yes.

**Comment by DavidMansolino** [comment]
:+1:

**Comment by omichel** [comment]
:+1:

**Pull request merged**
