### PR TITLE
Better robot menu

### PR DESCRIPTION
**Pull request by remidhum**
Improved robot visibility in menu by using images.

Preview: https://www.cyberbotics.com/doc/guide/robots?version=emhancement-better-robot-menu

### CODE REVIEW

**Comment by remidhum** [comment]
👍

**Comment by remidhum** [comment]
Since more robots will be added in the future, I think the robots should be ordered alphabetically in the menu.

**Comment by remidhum** [comment]
👍

**Comment by remidhum** [comment]
I have noticed the images do not all have the same width causing the links to not be aligned. 
Fixing the width of the images on this page would make for better aesthetics but new images should be added for all the robots ...

**Comment by fabienrohrer** [comment]
👍

**Pull request merged**
