### PR TITLE
Add missing note.png file in the offline documentation

### LINKED ISSUE #353: Missing 'note.png' icon in offline documentation
In the online documentation, notes have an icon.
For example at the bottom of the Accelerometer page:
https://www.cyberbotics.com/doc/reference/accelerometer

But this icon is not displayed in the offline documentation.

### PR DESCRIPTION
**Pull request by fabienrohrer**
Fix #353

### CODE REVIEW

**Comment by fabienrohrer** [comment]
(still some alignment issue).

**Comment by stefaniapedrazzi** [comment]
> (still some alignment issue).

could you post a screenshot?
I think there are exactly the same alignment issues (padding) when I include it in the web interface.
If yes, then we should add a class in the webots_doc.css.

**Comment by fabienrohrer** [comment]
I have this kind of misalignment, and I didn't investigate why yet:

capture d ecran 2017-06-20 a 09 15 26

**Comment by fabienrohrer** [comment]
Fixing the padding as you propose is fixing the issue.

**Comment by stefaniapedrazzi** [comment]
Ok, it is the same as in the web interface documentation.
At the moment I solved it in #351 by adding two classes to the #center element:
https://github.com/omichel/webots-doc/pull/351/files#diff-fdd62affd948d0ed17987bb9556bccf5R118

**Comment by fabienrohrer** [comment]
Ok, then it's probably simpler if you merge my patch in #351 (add the icon and a second url for the icon). Do you agree?

**Comment by stefaniapedrazzi** [comment]
I can add the classes in this PR.
Because the other PR in on the develop branch.

**Comment by fabienrohrer** [comment]
Ok, it seems good too. Could I let you complete this PR, then?

**Comment by stefaniapedrazzi** [comment]
Yes

**Comment by stefaniapedrazzi** [comment]
If this last change is fine I will approve this PR:
:+1:

**Comment by fabienrohrer** [comment]
👍  Perfect, thank you.

**Pull request merged**
