### PR TITLE
Fix Vehicle typedef Names.

### PR DESCRIPTION
**Pull request by DavidMansolino**
Dual PR omichel/webots#7432

### CODE REVIEW

**Comment by DavidMansolino** [comment]
Not sure whether we want to call them WbCar.../WbDriver... or WbuCar/WbuDriver... I have a slight preference for the second option which seems more coherent with the rest of the vehicle API.
@All, what yo you think?

**Comment by stefaniapedrazzi** [comment]
Given that we are changing them, I would personally address the issue globally and make a "final" decision on how we want to handle all the utility libraries, i.e. address https://github.com/omichel/webots/issues/4134 not only for the types but also for functions.

**Comment by DavidMansolino** [comment]
I agree it is good to take a decision about this and stick to it but I would like to keep this PR focused on typedef names only (especially because the dual PR is focused on this and because according to omichel/webots#4134 libcar and libdriver are already correct).

**Comment by stefaniapedrazzi** [comment]
So then the type cannot be `WbCar.../WbDriver..` because only libController functions and types should start with `Wb`.
If we decide that all the utility libraries have to be external and use prefix `wbu`, then all the libCar/libDriver types should have the `Wbu` prefix and not `Wb`.

**Comment by omichel** [comment]
Yes, the `Wbu` prefix is the way to go to solve this issue.

**Comment by DavidMansolino** [comment]
👍

**Pull request merged**
