### PR TITLE
Fix recently added ESLint issues

### PR DESCRIPTION
**Pull request by fabienrohrer**
Preview: https://www.cyberbotics.com/doc/guide/robots?version=fix-eslint-issues

### CODE REVIEW

**Comment by fabienrohrer** [comment]
Note: I just remarked that `.eslintrc.json` is defined in the webots repo and not in this repo (which seems good to avoid duplication). This means that if you work in a local fork of this repo outside the webots repo, ESLint is disabled.

**Comment by fabienrohrer** [comment]
👍

**Comment by tn12787** [comment]
It would be great to add tests that use eslint in the doc test suite to avoid this kind of problem!

**Comment by fabienrohrer** [comment]
Indeed, but the location of .eslintrc.json is an issue to do so, because travis is not aware of the webots repo. Duplicating .eslintrc.json will cause other issues.

**Comment by fabienrohrer** [comment]
If you agree, I'm just opening an issue for this for now.

**Comment by tn12787** [comment]
Sounds good to me!

**Comment by fabienrohrer** [comment]
=> #773

Meanwhile, I recommend to merge this PR.

**Pull request merged**
