### PR TITLE
Support reference to external repository

### PR DESCRIPTION
**Pull request by omichel**
Addresses #128.

### CODE REVIEW

**Comment by omichel** [comment]
The Travis test is failing due to some timeout problem with `local_exporter.py`.

**Comment by fabienrohrer** [comment]
It seems that http://cyberbotics.com/jquery-ui/1.11.4/theme.css is inaccessible.

**Comment by omichel** [comment]
But it is accessible. I can get it...

**Comment by omichel** [comment]
Yes, the URL is wrong. It should be https://www.cyberbotics.com/jquery-ui/1.11.4/theme.css

**Comment by fabienrohrer** [comment]
Strange, the first time I tried, I had issues, but now I can get it too.

**Comment by fabienrohrer** [comment]
This timeout is failing:
https://github.com/omichel/webots-doc/blob/master/local_exporter.py#L42

**Comment by fabienrohrer** [comment]
The same timeout failed again on another file.
Maybe the Travis network is saturated or so!? Increasing the timeout should solve the issue, but it's a dirty patch.

**Comment by omichel** [comment]
Shall I try this?

**Comment by fabienrohrer** [comment]
Yes, gladly. I would put a timeout of 30 seconds or so.

**Comment by DavidMansolino** [comment]
I have the same timeout issue on #132

**Comment by omichel** [comment]
Well, it doesn't seem to fix the problem... :unamused:

**Comment by omichel** [comment]
I believe it is not necessary to support a renaming of the webots-doc repository as it is very unlikely to happen (why users would do that?). Instead, they would rather create different branches.

:+1:

**Comment by omichel** [comment]
:+1:

**Comment by fabienrohrer** [comment]
👀

**Comment by fabienrohrer** [comment]
> why users would do that?

Although it's useless, as this is a GitHub feature, soon or later a user will do it :-)
But we can indeed not take care about this very irregular case.

**Comment by fabienrohrer** [comment]
👍  (seems to work like a charm)

**Comment by omichel** [comment]
:+1:

**Pull request merged**
