### PR TITLE
Fixed typos

### PR DESCRIPTION
**Pull request by omichel**
Following-up on https://github.com/omichel/webots/issues/7027, here is a proposal for PROTO design guidelines. 
Test link: https://www.cyberbotics.com/doc/reference/proto-design-guidelines?version=feature-proto-design-guidelines

### CODE REVIEW

**Comment by fabienrohrer** [comment]
I would apply this in develop, because none of our PROTOs are respecting these guidelines :-/

**Comment by omichel** [comment]
Ok, so I will open a new PR aiming at the develop branch.
Meanwhile, this PR still fixes a couple of typos in the revision 1 branch.

**Comment by fabienrohrer** [comment]
Thank you, it seems better.

**Comment by omichel** [comment]
👍

**Pull request merged**
