### PR TITLE
Improve doc css

### PR DESCRIPTION
**Pull request by tn12787**
This PR is an attempt to improve the look of the doc, to make it a little more modern.

### CODE REVIEW

**Comment by tn12787** [comment]
### First Screenshot

accent color

**Comment by tn12787** [comment]
I chose a reddish color here to go with the fact that our main logo is red and black - I figured it could work as subtle reinforcement of our branding.

**Comment by tn12787** [comment]
Updated screenshot.

**Comment by omichel** [comment]
I personally find the red color pretty aggressive and would tend to prefer the blue one we started to use for code sections...

**Comment by tn12787** [comment]
Okay, I will try with a gentler color.

**Comment by tn12787** [comment]
### Gentler Blue

softerblue

**Comment by fabienrohrer** [comment]
I also prefer the blue color.

**Comment by tn12787** [comment]
### More Refined Screenshot

blue bg

**Comment by tn12787** [comment]
👍

**Comment by tn12787** [comment]
[Current Snapshot](https://www.cyberbotics.com/doc/reference/camera?version=enhancement-better-doc-css)

**Comment by tn12787** [comment]
👍

**Comment by tn12787** [comment]
👍 after comments from @omichel.

**Comment by tn12787** [comment]
👍

**Comment by fabienrohrer** [comment]
There are some font issues on macOS when embedded in Webots.

**Comment by tn12787** [comment]
So in short, `QtWebKit` on `macOS` still cannot load custom ttfs, it seems.

The previous behaviour has been restored for now, so there are no regressions.

**Comment by tn12787** [comment]
👍

**Pull request merged**
