### PR TITLE
Merge webots8.5.5 into develop

### PR DESCRIPTION
**Pull request by stefaniapedrazzi**
Fix conflicts:
* automobile/openstreetmap-importer.md
* css/webots-doc.css
* js/viewer.js

### CODE REVIEW

**Comment by stefaniapedrazzi** [comment]
In `automobile/openstreetmap-importer.md` I used the develop version.
@fabienrohrer: it would be good if you could look at the conflicts resolution and check I didn't remove any changes introduced in the master/webots8.5.5 branch

**Comment by stefaniapedrazzi** [comment]
:+1:

**Comment by fabienrohrer** [comment]
👀

**Comment by fabienrohrer** [comment]
I think only this modification has been wrongly dropped:

https://github.com/omichel/webots-doc/pull/346/files

I'm restoring it.

**Comment by stefaniapedrazzi** [comment]
Thank you

**Comment by fabienrohrer** [comment]
And this one too:

https://github.com/omichel/webots-doc/pull/347/files

**Comment by fabienrohrer** [comment]
But this last one should be integrated with my work.

**Comment by fabienrohrer** [comment]
Done in 487c1b6

**Pull request merged**
