### PR TITLE
Use javascript/CSS to create a resizable/closable menu

### PR DESCRIPTION
**Pull request by fabienrohrer**
Alternative to #115

### CODE REVIEW

**Comment by fabienrohrer** [comment]
Here is the best way to do this: to put a div in-between the left and the center divs with mouse events.

Demo here (still some bugs):
https://www.cyberbotics.com/doc/guide/sample-webots-applications

**Comment by omichel** [comment]
That looks indeed promising...

**Comment by fabienrohrer** [comment]
It seems to work well now:
https://www.cyberbotics.com/doc/guide/

**notes:**

- the internal layout of the menu has a better alignement
- the FTP files are updated
- I used a style for the handle which is close to the Webots handles:

capture d ecran 2016-07-06 a 15 46 54

**Comment by fabienrohrer** [comment]
👍

**Comment by stefaniapedrazzi** [comment]
It works fine, but I personally think that the minimum width is too big for the dock widget documentation.
Moreover if the the section title text is cut it seems there is not horizontal scrollbar.

**Comment by fabienrohrer** [comment]
Ok, I will try to improve this.

**Comment by omichel** [comment]
I agree there is something strange happening with the minimal width which is user unfriendly.
I believe we should allow the user to drag the bar to a very small size and only after he releases the mouse button we should either keep the selected size (if above the minimum) or completely hide the menu (if below the minimum). Hiding the menu while the user is dragging is user unfriendly...

I am not sure a horizontal scroll bar for the menu is useful as the user has always the possibility to drag the vertical size bar if he wants to read the full text, which is very intuitive. A scroll bar would add some unnecessary stuff in my point of view.

**Comment by omichel** [comment]
The sugar would be that when releasing the resize bar at a width below the minimum, the menu would get hidden through a quick animation (like if the user had continued to drag the size bar until the menu is not visible any more). But maybe that's not strictly necessary.

**Comment by omichel** [comment]
Otherwise, it looks really very good :smile:.

**Comment by omichel** [comment]
Maybe another improvement to be more user friendly. When trying to go beyond the maximum menu width, we shouldn't prevent the user from further dragging the resize bar. Only after he releases it, we should resize the menu to its maximum width. This is very similar to the management of the minimum width.

**Comment by fabienrohrer** [comment]
Thank you.

Just a side note before going on: I copied the min width mechanism on the scene tree view: they currently act the same (except the threshold are not identical, and the scene tree has an horizontal scroll bar)

**Comment by omichel** [comment]
I see. So, maybe forget what I explained about resize management and let's try to make it similar to what happens in Qt.

**Comment by omichel** [comment]
I noticed an important difference between Qt/Webots and the web resize bar:
In Qt/Webots (tested on Windows), the pane is resized to 0 only after the mouse X coordinate goes below minimum_width / 2. Whereas in the web page, that happens when the mouse X coordinates goes below minimum_width. This is a small detail, but makes it more user friendly in Qt/Webots.

**Comment by fabienrohrer** [comment]
Ok, so regarding to all the comments, I propose if you agree to do a new iteration by:
- [ ] implementing the resize pane bellow `minimum_width / 2` instead of `minimum_width`
- [ ] add some horizontal scroll bars when required
.. and to let you test again if this is better or not.

**Comment by omichel** [comment]
Perfect. Thanks. :smile:

**Comment by fabienrohrer** [comment]
I implemented the last propositions, and still reduced the differences with Qt layout (same menu and handle width) and behavior:

capture d ecran 2016-07-06 a 17 05 40

**Comment by fabienrohrer** [comment]
👍

**Comment by omichel** [comment]
One remark: the equivalent sign `≡` doesn't appear in the web version, is that correct?

**Comment by omichel** [comment]
The horizontal scroll bar sometimes appear bogus. In this case for example, after some random resizes, only a small part of it is visible and I cannot see more by using the vertical scroll bar. Weird.
untitled
Anyhow, I am still not convinced that this horizontal scroll bar is very useful. It makes things more complex both for us and for the user.

**Comment by fabienrohrer** [comment]
> One remark: the equivalent sign ≡ doesn't appear in the web version, is that correct?

Yes, I had issues to align it vertically, and added it mainly to match the Webots layout.

> Anyhow, I am still not convinced that this horizontal scroll bar is very useful. It makes things more complex both for us and for the user.

I'm also not convinced. A good menu is supposed to be always readable; for me it's more a matter of setting a good min width.

**Comment by fabienrohrer** [comment]
I dropped the horizontal scrollbar.

👍

**Comment by fabienrohrer** [comment]
New TODO points after a review with Olivier:

- [ ] The handle should remain blue during the entire drag.
- [ ] When resizing the window, the menu width should stay the same.
- [ ] The handle size should be adjusted again on the Webots handle size.

**Comment by fabienrohrer** [comment]
Note: the handle with on the online version was too narrow, because of bootstrap which was overriding the `box-sizing` rule.

**Comment by fabienrohrer** [comment]
Note: now, the menu width is initialized at 20% of the window location, and is no more affected by the window resize, solving some resizing issues.

**Comment by fabienrohrer** [comment]
👍

**Comment by omichel** [comment]
:+1: Perfect!

**Pull request merged**
