### PR TITLE
Fix references to wbr_set_refresh_rate()

### PR DESCRIPTION
**Pull request by fabienrohrer**
Ditto

### CODE REVIEW

**Comment by DavidMansolino** [comment]
Shouldn't this be done in PR #4073 directly ?

**Comment by fabienrohrer** [comment]
No, we're here in `webots-doc` ;-)

**Comment by DavidMansolino** [comment]
Yes, I realized this just after pressing the 'comment' button.

**Comment by fabienrohrer** [comment]
👍

**Comment by DavidMansolino** [comment]
:+1:

**Pull request merged**
