### PR TITLE
Merge webots8.6.3 into develop

### PR DESCRIPTION
**Pull request by fabienrohrer**
👍

### CODE REVIEW

**Comment by stefaniapedrazzi** [comment]
There are also changes in webots-doc@master to be forwarded to webots8.6.3 and develop branches.

**Comment by fabienrohrer** [comment]
Ok, you're right, let's do this first. I'm creating the PR.

**Comment by stefaniapedrazzi** [comment]
It already exists: #497

**Comment by fabienrohrer** [comment]
👍

**Pull request merged**
