### PR TITLE
Add instructions to install Python OpenCV

### PR DESCRIPTION
**Pull request by stefaniapedrazzi**
Related with https://github.com/omichel/webots/pull/4960.

TODO:
* [x] linux instructions
* [x] Windows instructions
* [x] macOS X instructions

### CODE REVIEW

**Comment by stefaniapedrazzi** [comment]
@fabienrohrer could you please add the instructions to install python OpenCV on macOS?

**Comment by fabienrohrer** [comment]
`python-opencv` cannot be installed easily on macOS because it seems not to be a member of pip. Using `homebrew` seems to be the official way to do this, but I'm hesitating because of the high risk to override the Python system.

**Comment by stefaniapedrazzi** [comment]
I saw in the text you wrote that is was correct, but not in the comment:
the pip package is called `opencv-python` (Ubuntu 16.04 and Windows), and `python-opencv` is the APT package to be installed on Ubuntu 14.04.

Note that with pip it seems that OpenCV 3 is installed, but this should not be a problem.

**Comment by fabienrohrer** [comment]
Finally, this was an issue about sudo/user in my system. This is now working with these instructions.

**Comment by fabienrohrer** [comment]
👍

**Comment by stefaniapedrazzi** [comment]
:+1:

**Pull request merged**
