### PR TITLE
Feature Charts

### PR DESCRIPTION
**Pull request by DavidMansolino**
Follow-up of #670 on master.
Fix issue #8.

Renaming tasks:
  - [x] Update node chart for master.
  - Update the other charts:
    - [x] api_overview
    - [x] controller_plugin
    - [x] motor_control
    - [x] physics_execution_scheme
    - [x] tutorial_4_wheels_highlevel
    - [x] tutorial_4_wheels_lowlevel
    - [x] tutorial_ackermann_vehicle ?
    - [x] tutorial_compound_solid
    - [x] tutorial_def_use_shape
    - [x] tutorial_feedback_loop ?
    - [x] tutorial_solid
  - [x] Documentation: https://github.com/omichel/webots-doc/wiki/Style-and-conventions#charts
  - [x] Upload files to the ftp (`mermaidAPI` and `doc.php`)
  - [x] Fix size of text if link
  - [x] Fix possibility to insert in figure

To test:
https://www.cyberbotics.com/doc/guide/controller-plugin?version=feature-chart#the-simplest-model-of-a-rigid-body-in-webots-having-a-graphical-representation-shape-a-physical-bound-boundingobject-and-being-in-the-dynamical-environment-physics
https://www.cyberbotics.com/doc/guide/cpp-java-python?version=feature-chart#the-simplest-model-of-a-rigid-body-in-webots-having-a-graphical-representation-shape-a-physical-bound-boundingobject-and-being-in-the-dynamical-environment-physics
https://www.cyberbotics.com/doc/guide/tutorial-2-modification-of-the-environment-20-minutes?version=feature-chart#the-simplest-model-of-a-rigid-body-in-webots-having-a-graphical-representation-shape-a-physical-bound-boundingobject-and-being-in-the-dynamical-environment-physics
https://www.cyberbotics.com/doc/guide/tutorial-2-modification-of-the-environment-20-minutes?version=feature-chart#def-use-mechanism-applied-on-the-shape-node-of-a-solid
https://www.cyberbotics.com/doc/guide/tutorial-4-more-about-controllers-20-minutes?version=feature-chart#uml-state-machine-of-a-simple-feedback-loop
https://www.cyberbotics.com/doc/guide/tutorial-5-compound-solid-and-physics-attributes-15-minutes?version=feature-chart
https://www.cyberbotics.com/doc/guide/tutorial-6-4-wheels-robot?version=feature-chart
https://www.cyberbotics.com/doc/reference/chart?version=feature-chart
https://www.cyberbotics.com/doc/reference/execution-scheme?version=feature-chart
https://www.cyberbotics.com/doc/reference/motor?version=feature-chart

### CODE REVIEW

**Comment by DavidMansolino** [comment]
The other charts are now very easy to update in just a few lines:
**old:**

**new:**

**code:**
```
%chart
graph BT
  Java["Java API (SWIG generated)"] --> CPP[C++ API]
  Python["Python API (SWIG generated)"] --> CPP
    CPP --> C["C API (implemented in libcontroller)"]
    Matlab[Matlab API] --> C
      C --> Webots["Webots (binary interface)"]
%end
```

**Comment by tn12787** [comment]
This looks great, nice job!

**Comment by fabienrohrer** [comment]
It sounds very good.

**Comment by DavidMansolino** [comment]
@all, should we keep the original *.dia file?
(if we need a png we can easily generate one from the md file using atom)

**Comment by omichel** [comment]
No, I would drop the old *.dia files.

**Comment by DavidMansolino** [comment]
There are a couple of dia files I was not able to remove because they are clearly not [flow chart](https://mermaidjs.github.io/flowchart.html) or [sequence diagram](https://mermaidjs.github.io/sequenceDiagram.html) such as this one:
light_sensor

**Comment by DavidMansolino** [comment]
I still need to update the online doc (upload mermaidAPI and update doc.php) but it would be nice to have a first review before updating the production files.

👍

**Comment by fabienrohrer** [comment]
- The charts, especially the node chart, is not supporting well window resizing (it becomes unreadable). We could certainly adopt the same rule as for the code statements, to set a min-width for the graphs, and if reached to display horizontal/vertical scroll bars.
- I think that the chart is not well released. When loading the page and naviguating to other, I have some graph weird ghosts. To reproduce:

    1. In firefox, open the local file: file:///Users/fabien/develop/webots-master/doc/local_index.html?url=localhost&book=reference&page=chart
    2. click then on the Appearance page from the menu
    3. scroll down
    4. the following artifacts should appear:

         capture d ecran 2018-03-07 a 17 41 36

- The graphs are not loaded when embed in Webots, but I think its normal, because it's not yet downloaded well locally (because not yet on the FTP).

**Comment by DavidMansolino** [comment]
Thank you for the tests.

> The charts, especially the node chart, is not supporting well window resizing (it becomes unreadable). We could certainly adopt the same rule as for the code statements, to set a min-width for the graphs, and if reached to display horizontal/vertical scroll bars.

You are speaking about the size of the text right?

> I think that the chart is not well released. When loading the page and naviguating to other, I have some graph weird ghosts.

I can indeed reproduce this. It is indeed most probably a wrong release.

> The graphs are not loaded when embed in Webots, but I think its normal, because it's not yet downloaded well locally (because not yet on the FTP).

Actually it is working fine for me, did you run the local exporter?
capture_w

**Comment by DavidMansolino** [comment]
> I think that the chart is not well released. When loading the page and naviguating to other, I have some graph weird ghosts.

This should now be fixed 😃

**Comment by fabienrohrer** [comment]
> You are speaking about the size of the text right?

Yes, if the size is slightly too small, the graph is simple not readable.

> This should now be fixed 😃

I confirm it's fixed.

> Actually it is working fine for me, did you run the local exporter?

It's working, sorry for this.

**Comment by DavidMansolino** [comment]
> Yes, if the size is slightly too small, the graph is simple not readable.

Ok, I can indeed reproduce this when setting a small window size. I will try your suggestion about min-width and horizontal scroll bar  (I don't think we need vertical).

**Comment by DavidMansolino** [comment]
👍

**Comment by fabienrohrer** [comment]
All the issues I mentioned earlier are fixed, thank you. The graphs are now readable from a low resolution window. 
I think that setting a background color for the graphs would be better. If the graph is not entirely visible, it's difficult to understand where are its limits.

**Comment by DavidMansolino** [comment]
> I think that setting a background color for the graphs would be better. If the graph is not entirely visible, it's difficult to understand where are its limits.

Good idea!

**Comment by DavidMansolino** [comment]
With background:
capture


👍

**Comment by DavidMansolino** [comment]
Ready to test in production:
https://www.cyberbotics.com/doc/guide/controller-plugin?version=feature-chart#the-simplest-model-of-a-rigid-body-in-webots-having-a-graphical-representation-shape-a-physical-bound-boundingobject-and-being-in-the-dynamical-environment-physics
https://www.cyberbotics.com/doc/guide/cpp-java-python?version=feature-chart#the-simplest-model-of-a-rigid-body-in-webots-having-a-graphical-representation-shape-a-physical-bound-boundingobject-and-being-in-the-dynamical-environment-physics
https://www.cyberbotics.com/doc/guide/tutorial-2-modification-of-the-environment-20-minutes?version=feature-chart#the-simplest-model-of-a-rigid-body-in-webots-having-a-graphical-representation-shape-a-physical-bound-boundingobject-and-being-in-the-dynamical-environment-physics
https://www.cyberbotics.com/doc/guide/tutorial-2-modification-of-the-environment-20-minutes?version=feature-chart#def-use-mechanism-applied-on-the-shape-node-of-a-solid
https://www.cyberbotics.com/doc/guide/tutorial-4-more-about-controllers-20-minutes?version=feature-chart#uml-state-machine-of-a-simple-feedback-loop
https://www.cyberbotics.com/doc/guide/tutorial-5-compound-solid-and-physics-attributes-15-minutes?version=feature-chart
https://www.cyberbotics.com/doc/guide/tutorial-6-4-wheels-robot?version=feature-chart
https://www.cyberbotics.com/doc/reference/chart?version=feature-chart
https://www.cyberbotics.com/doc/reference/execution-scheme?version=feature-chart
https://www.cyberbotics.com/doc/reference/motor?version=feature-chart


👍

**Comment by fabienrohrer** [comment]
In some size conditions, it seems that `mermaidGraph0Div` is smaller than its content:

capture d ecran 2018-03-08 a 14 24 23

**Comment by fabienrohrer** [comment]
The charts look really good. The hyperlinks are awesome.

**Comment by DavidMansolino** [comment]
> In some size conditions, it seems that mermaidGraph0Div is smaller than its content:

I can indeed reproduce this with the online doc. I will check what is hapenning.

**Comment by DavidMansolino** [comment]
:+1:

**Pull request merged**
