### PR TITLE
Fix blockquote font-size for the online version

### PR DESCRIPTION
**Pull request by fabienrohrer**
Fix partially #117

### CODE REVIEW

**Comment by fabienrohrer** [comment]
In the online doc, `bootstrap` is overriding `font-size` of the block quotes. Overriding `font-size` again in the webots CSS is a solution to solve this.

**Comment by fabienrohrer** [comment]
The code doesn't have a different font-size, but looks different because a monospaced font is used.

**Comment by fabienrohrer** [comment]
I also aligned the quote left border with the paragraphs.

**Comment by fabienrohrer** [comment]
I propose to accept already this (as a hot fix), and to do a second iteration about improving the quotes rendering as proposed in #117.

**Comment by fabienrohrer** [comment]
👍

**Comment by omichel** [comment]
:+1:

**Pull request merged**
