### PR TITLE
Document Robotis-op Matlab Remote Control and Robot Window Issue

### PR DESCRIPTION
**Pull request by DavidMansolino**
https://www.cyberbotics.com/doc/guide/robotis-op2?version=fix-robotis-op-matlab#symmetry-wbt

https://www.cyberbotics.com/doc/guide/epuck?version=fix-robotis-op-matlab#bluetooth-remote-control

Linked to omichel/webots#6579

### CODE REVIEW

**Comment by DavidMansolino** [comment]
👍

**Comment by omichel** [comment]
:eyes:

**Comment by omichel** [comment]
Maybe a similar documentation should be added in the e-puck section as well.

**Comment by DavidMansolino** [comment]
👍

**Pull request merged**
