### PR TITLE
Merge master to develop

### PR DESCRIPTION
**Pull request by tn12787**
conflicts:

```
doc.php
reference/matlab-api.md
```

### CODE REVIEW

**Comment by tn12787** [comment]
👍

**Comment by tn12787** [comment]
👎 my local master was out of date.

**Comment by fabienrohrer** [comment]
Sorry to quible, but normally we have to do an intermediate stage:
1. Merge `master` -> `webots-r2018a-revision-1`
2. Merge `webots-r2018a-revision-1` -> `develop`

**Comment by tn12787** [comment]
I see, thanks for letting me know!

**Pull request closed without merging**
