### PR TITLE
Added test for pi unicode character in MD files

### PR DESCRIPTION
**Pull request by omichel**
Test to ensure we don't encounter #711 any more.

### CODE REVIEW

**Comment by fabienrohrer** [comment]
(if you would like, I can do it on Monday.)

**Comment by omichel** [comment]
Yes, gladly. I am not sure why this doesn't work as I followed your example with the advertising keyword, but it seems it doesn't work...

**Comment by fabienrohrer** [comment]
The Travis test successfully failed here: https://travis-ci.org/omichel/webots-doc/builds/355952362?utm_source=github_status&utm_medium=notification

**Comment by fabienrohrer** [comment]
> Yes, gladly. I am not sure why this doesn't work as I followed your example with the advertising keyword, but it seems it doesn't work...

The test you copied was about to check no prohibited keyword was appearing in the MD filename, not it's content.

**Comment by fabienrohrer** [comment]
👍

**Comment by omichel** [comment]
:eyes:

**Comment by omichel** [comment]
👍 (I can't approve as I am the author of this PR).

**Pull request merged**
