### PR TITLE
Documentation of the custom shaders and multitexturing feature (to develop)

### PR DESCRIPTION
**Pull request by fabienrohrer**
- [x] Document new nodes and fields
    - [x] ComposedShader
    - [x] ShaderPart
    - [x] Uniform
    - [x] MultiTexture
    - [x] Appearance.shaders
    - [x] Appearance.texture (can be a MultiTexture)
- [x] Document X3Dom export
- [x] Document limitations
- [x] Fix menus
- [x] Add new nodes into the node chart

### CODE REVIEW

**Comment by fabienrohrer** [comment]
👍  (wait on the acceptance of the corresponding branch on the webots repo)

**Comment by omichel** [comment]
:+1:

**Comment by fabienrohrer** [comment]
Modifications since last review:
- updated the dia diagram to add the new LensFlare node in the new layout.

**Comment by fabienrohrer** [comment]
👍

**Pull request merged**
