### PR TITLE
Merge ROBOTIS book in user guide

### PR DESCRIPTION
**Pull request by fabienrohrer**
Preview: https://www.cyberbotics.com/doc/guide/robotis-op2?version=enhancement-merge-robotis-book-in-user-guide

- [x] Merge ROBOTIS book in user guide
- [x] Shrink Robotis OP2 page is possible (tables / figures)
- [x] Uniformize the Robotis OP2 page with the others.
- [x] Deal with DARwIn-OP robot
- [x] Remove book references.

### CODE REVIEW

**Comment by fabienrohrer** [comment]
For now I just copied all the ROBOTIS book in the robotis-op2 page (except obvious duplicates): https://www.cyberbotics.com/doc/guide/robotis-op2?version=enhancement-merge-robotis-book-in-user-guide

I can still shrink it in many ways.

Do you think it's size is reasonable? I think yes.

**Comment by omichel** [comment]
Yes, I believe the size of the page is not a problem.

**Comment by fabienrohrer** [comment]
👍

**Comment by omichel** [comment]
:eyes:

**Comment by omichel** [comment]
There is like a bug when you select "Robotis OP2" in the margin, it doesn't get selected. Instead the "DARwIn-OP" menu item is selected.

**Comment by fabienrohrer** [comment]
Well spotted. The menu is not powerful enough to support two menu items pointing on a single page. I think the simplest solution is to restore the DARwIn-OP page and to invite the user to read the ROBOTIS OP2 page.

**Comment by fabienrohrer** [comment]
👍

**Comment by omichel** [comment]
I believe we should add this video: https://www.youtube.com/watch?v=y_o_tSwBT-E

**Comment by fabienrohrer** [comment]
> I believe we should add this video: https://www.youtube.com/watch?v=y_o_tSwBT-E

Done here: https://www.cyberbotics.com/doc/guide/robotis-op2?version=enhancement-merge-robotis-book-in-user-guide#presentation-movies

👍

**Pull request merged**
