### PR TITLE
Nao standardization

### PR DESCRIPTION
**Pull request by remidhum**
Applying the standards from the Pioneer 3-AT and 3-DX to the Nao page.
The constests have been added on this page as a dedicated page does not yet exist.

Preview: https://www.cyberbotics.com/doc/guide/using-the-nao-robot?version=enhancement-nao-standardization

### CODE REVIEW

**Comment by remidhum** [comment]
👍 
https://www.cyberbotics.com/doc/guide/using-the-nao-robot?version=enhancement-nao-standardization

**Comment by omichel** [comment]
I believe we should make two sections for this robot: one for use with the Webots API and another for use with the NAOqi interface (and explain it is deprecated).

**Comment by remidhum** [comment]
Should this be done in a separate PR?

**Comment by omichel** [comment]
Yes, I think so, so you can merge this one.

**Pull request merged**
