### PR TITLE
Itemized menu items

### PR DESCRIPTION
**Pull request by fabienrohrer**
Improved readability of the menu items description by itemizing them.

Before: https://www.cyberbotics.com/doc/guide/the-user-interface
After: https://www.cyberbotics.com/doc/guide/the-user-interface?version=enhancement-menu-description-format

### CODE REVIEW

**Comment by fabienrohrer** [comment]
Note: I'm postponing the "one line per sentence" rule to another PR in order to increase the PR readability.

**Comment by fabienrohrer** [comment]
👍

**Comment by stefaniapedrazzi** [comment]
:eyes:

**Comment by fabienrohrer** [comment]
I think items and indentation are better, because the shape of the chapter is more logical. For example, the description of the `File` menu does not appear at the same indentation as the description of the `New world` menu, or the `Revert world` note is now correctly aligned.

I think you're right about the code font which is not appropriated in this case. I'm trying this here.

**Comment by fabienrohrer** [comment]
Using bold to highlight the item topic is indeed more readable in my point of view.

**Comment by fabienrohrer** [comment]
👍

**Pull request merged**
