### PR TITLE
Fix word wrapping on code blocks in embedded doc

### PR DESCRIPTION
**Pull request by tn12787**
Fix horizontal scrollbars on embdedded doc.

### CODE REVIEW

**Comment by tn12787** [comment]
I'm starting to really worry about boostrap applying endless rules on top of the doc css, it makes developing the actual doc css error prone (like this bug) and rather tedious. I think the doc css should apply a css reset   of some kind to undo bootstrap's influence.

**Comment by fabienrohrer** [comment]
I agree with this observation, and open an issue there: https://github.com/omichel/webots-doc/issues/795

**Comment by tn12787** [comment]
:+1:

**Comment by DavidMansolino** [comment]
👀

**Pull request merged**
