### PR TITLE
Fix misc issues with urls and anchors

### LINKED ISSUE #55: Link on the same page working only first time [Firefox]
If you go to this page: https://www.cyberbotics.com/doc/reference/accelerometer and click on one of the `Accelerometer` links, it work fine (position modified and url changed to https://www.cyberbotics.com/doc/reference/accelerometer#accelerometer) but then if you press again on a `Accelerometer` links it doesn't do anything.

Note that I was able to reproduce this on Firefox (Linux) but on Chrome everything is working fine.

### PR DESCRIPTION
**Pull request by fabienrohrer**
- [x] Fix #55: on firefox the second click on internal anchors is not dealt correctly
- [x] Fix default values in case of issues
- [x] Fix behavior when starting the local doc without arguments

### CODE REVIEW

**Comment by fabienrohrer** [comment]
👍

**Comment by DavidMansolino** [comment]
:eyes:

**Comment by DavidMansolino** [comment]
I think using https://www.cyberbotics.com/doc/reference/accelerometer?version=fix-urls-and-anchors for testing is not a good idea or should it work ?

**Comment by fabienrohrer** [comment]
No, I didn't upload the new version yet, but I'm doing it right now :-)

**Comment by fabienrohrer** [comment]
Ok, I uploaded the file, please remove your cache.

**Comment by DavidMansolino** [comment]
Thank you.

Unfortunately now the link doesn't work at all (even on the first click) on Firefox

**Comment by fabienrohrer** [comment]
Ok, it's working only if the anchor is set initially:
https://www.cyberbotics.com/doc/reference/accelerometer?version=fix-urls-and-anchors#accelerometer

I'm fixing this.

**Comment by DavidMansolino** [comment]
I can confirm it's working fine is the anchor is set.

**Comment by fabienrohrer** [comment]
Ok, this seems to be fixed now:
https://www.cyberbotics.com/doc/reference/accelerometer

**Comment by fabienrohrer** [comment]
👍

**Comment by DavidMansolino** [comment]
Yes, it is fixed, but the anchor is not added any more in the url, is this normal ?

**Comment by fabienrohrer** [comment]
No :-) 
Well spotted, I'm fixing this.

**Comment by fabienrohrer** [comment]
It should be fixed now.
👍

**Comment by DavidMansolino** [comment]
It is working perfectly now :smiley: 

:+1:

**Pull request merged**
