### PR TITLE
Move spinning_top.wbt to howto section.

### PR DESCRIPTION
**Pull request by fabienrohrer**
Dual PR: https://github.com/omichel/webots/pull/6853

### CODE REVIEW

**Comment by fabienrohrer** [comment]
👍

**Comment by fabienrohrer** [comment]
👍

**Comment by stefaniapedrazzi** [comment]
There are some conflicts, so maybe I have to approve this PR again after solving them.

**Comment by fabienrohrer** [comment]
Yes, this is because I just merged the PR about the supervisor trail. I'm fixing this right now.

**Comment by fabienrohrer** [comment]
👍

**Pull request merged**
