### PR TITLE
Hotfix: broken anchors in firefox

### PR DESCRIPTION
**Pull request by fabienrohrer**
Fix https://github.com/omichel/webots-doc/issues/816

Preview: https://www.cyberbotics.com/doc/guide/robotis-op2?version=hotfix-anchors-for-firefox#symmetry-wbt

### CODE REVIEW

**Comment by fabienrohrer** [comment]
I tried several solutions, and if I add the constraint to not modify wwi.css (which is wiser on master), I can only override this CSS rule.

I propose to accept this as-is, and to fix this in a cleaner way in develop (I will take care of this as soon as this PR is merged in develop) by removing this kind of general rules from wwi.css.

**Comment by omichel** [comment]
:eyes:

**Comment by fabienrohrer** [comment]
I'm still looking at a bug in the scroll computation.

**Comment by fabienrohrer** [comment]
I will do the other patch I was speaking about in another PR.

**Comment by fabienrohrer** [comment]
👍

**Pull request merged**
