### PR TITLE
Fixed URLs with custom repositories.

### LINKED ISSUE #151: Lost tag
Upon changing or clicking on a new section in  [here] (https://www.cyberbotics.com/doc/automobile/buildings?version=remidhum:doc-automobile-objects), the ID tag (i.e. `remidhum`) disappears. This causes some pages not to load up (`Advertising Board` in particular) and if refreshed, none of the pages load. 
However, as long as the page is not refreshed, the rest of the sections will correctly open even without the name tag. 

After a refresh (and a sub section change), the url is similar to this: 

> https://www.cyberbotics.com/doc/automobile/buildings?version=doc-automobile-objects

By adding `remidhum:` just after `version=` fixes the problem. 

> https://www.cyberbotics.com/doc/automobile/buildings?version=remidhum:doc-automobile-objects

### PR DESCRIPTION
**Pull request by fabienrohrer**
Attempt to fix #151

### CODE REVIEW

**Comment by fabienrohrer** [comment]
👍

**Comment by fabienrohrer** [comment]
To test:

- the links seem to propagate correctly the custom repos: https://www.cyberbotics.com/doc/automobile/buildings?version=remidhum:doc-automobile-objects
- on the link above, the `Advertising Board` link is prohibited due to AdBlocks. Disable it to check this. Check the rename in this url: https://www.cyberbotics.com/doc/automobile/billboard?version=fix-urls-with-custom-repository

👍

**Comment by DavidMansolino** [comment]
:eyes:

**Comment by DavidMansolino** [comment]
I am not sure how to test this, if I test in a branch from a custom repo then it will not contain this fix and it is not really useful to test on this branch.
How did you test it?

**Comment by fabienrohrer** [comment]
I uploaded the new doc.php and viewer.js on the FTP, so if you use this link https://www.cyberbotics.com/doc/automobile/buildings?version=remidhum:doc-automobile-objects, the links should remain on the remidhum repo (which was not the case before).

For the AdBlocks issue, you can only test it in this branch: https://www.cyberbotics.com/doc/automobile/billboard?version=fix-urls-with-custom-repository

**Comment by DavidMansolino** [comment]
Thank you for the explanation.

:+1:

**Pull request merged**
