### PR TITLE
Fix whitespace wrapping for code in paragraphs

### LINKED ISSUE #715: Code block text displayed outside page border
documentation_issue

### PR DESCRIPTION
**Pull request by tn12787**
fixes #715.

### CODE REVIEW

**Comment by tn12787** [comment]
preview: https://www.cyberbotics.com/doc/reference/proto-definition#fix-code-width

**Comment by tn12787** [comment]
real preview: https://www.cyberbotics.com/doc/reference/proto-definition?version=fix-code-width

**Comment by tn12787** [comment]
👍

**Comment by stefaniapedrazzi** [comment]
:eyes:

**Pull request merged**
