### PR TITLE
Fix highlight js dependency

### LINKED ISSUE #106: Syntax highlighting broken on the Cyberbotics website
The code should be highlighted when the markdown tags are referring to some language:

https://github.com/omichel/webots-doc/blob/master/guide/tutorial-4-more-about-controllers-20-minutes.md#program-a-controller
https://www.cyberbotics.com/doc/guide/tutorial-4-more-about-controllers-20-minutes#program-a-controller

This is working locally, but not on the Cyberbotics website.

Maybe it's due to #90!?

### PR DESCRIPTION
**Pull request by fabienrohrer**
- [x] Fix #106

    Use the following way to highlight the code in quotes:

    ```markdown
> my quote

> ```python
> import sys
> ```
    ```
- [x] Add missing language tags for code statements
- [x] Markdown style recommendations in the Wiki: https://github.com/omichel/webots-doc/wiki/Style-and-conventions#highlighted-code-in-quotes
- [x] Update to highlight 9.5.0:
    - [x] Add missing languages (matlab, tex, lua)
    - [x] Installation instructions in Webots wiki: https://github.com/omichel/webots/wiki/Javascript-dependencies
- [x] Restore the grey background for the code statements in the doc
- [x] Update the FTP

### CODE REVIEW

**Comment by fabienrohrer** [comment]
- Working locally
- Working in Github
    - https://github.com/omichel/webots-doc/blob/fix-highlight-in-quotes/automobile/cpp-and-java-wrappers-of-the-automobile-libraries.md
- Issues on our website (tags are well correctly generated, hljs seems to parse the code, but the highlight is not colored as expected):
    - https://www.cyberbotics.com/doc/automobile/cpp-and-java-wrappers-of-the-automobile-libraries?version=fix-highlight-in-quotes

**Comment by fabienrohrer** [comment]
> Issues on our website

This is because the highligh CSS is missing in `header.php`.

@omichel Could you add the following line in `header.php`? Thank you in advance.

```
<link type="text/css" rel="stylesheet" href="https://www.cyberbotics.com/highlight/9.2.0/default.min.css"/>
```

**Comment by omichel** [comment]
I believe it should be added in `doc.php`, not in `header.php` as it is specific to the documentation.

**Comment by omichel** [comment]
You should be able to do it yourself.

**Comment by omichel** [comment]
Ok, I just did it (in `doc.php`) and it works. However, the result is not as nice as in github. It is probably related with the pink background. I believe we should change it to light grey and increase the padding on the edges (like it is in github).

**Comment by omichel** [comment]
The syntax highlighting is not working on other pages such as https://www.cyberbotics.com/doc/reference/callback-functions?version=fix-highlight-in-quotes but I guess this PR is not yet complete with respect to this.

**Comment by fabienrohrer** [comment]
Interesting pages to test:
https://www.cyberbotics.com/doc/guide/tutorial-4-more-about-controllers-20-minutes?version=fix-highlight-in-quotes
https://www.cyberbotics.com/doc/guide/matlab?version=fix-highlight-in-quotes
https://www.cyberbotics.com/doc/automobile/car-library?version=fix-highlight-in-quotes
https://www.cyberbotics.com/doc/automobile/a-typical-openstreetmap-importer-configuration-file?version=fix-highlight-in-quotes
https://www.cyberbotics.com/doc/reference/speaker?version=fix-highlight-in-quotes (XML part)

**Comment by fabienrohrer** [comment]
👍

**Comment by omichel** [comment]
The node definitions (like the Speaker in the last example) don't have the nice indentation (padding or margin) like the code sections. We should try to make this more homogeneous.

Also, I personally don't like very much this pink background color (such a fancy color is almost never used in text editors, and hence looks a bit strange here). Why not simply use a light gray instead?

The rounded corners however look very nice...

**Comment by omichel** [comment]
In most source code example (and shells), we add one space to indent the code. This is not good. We should remove this space and add some padding to the corresponding `<div>` (this is related with my previous comment).

**Comment by fabienrohrer** [comment]
> Also, I personally don't like very much this pink background color (such a fancy color is almost never used in text editors, and hence looks a bit strange here). Why not simply use a light gray instead?

Grey has been restored, please update your cache.

**Comment by fabienrohrer** [comment]
> The rounded corners however look very nice...

I don't understand this comment, I didn't use rounded corners for the code. Is it a proposal you do to try?

**Comment by omichel** [comment]
I do see round corners (top left and bottom left on this screenshot, compared to the right where I sharply cut the image and hence the corner are square):
round

**Comment by fabienrohrer** [comment]
- the border-radius is strangely coming from the bootstrap CSS (not present in the local version). I added it in doc CSS.
- I modified the indentation of the code to match exactly the paragraph one. It's indeed probably more readable.

=> do you prefer the current result?

👍

**Comment by omichel** [comment]
It doesn't seem to work:
screenshot
The Speaker node definition is not indented like the code section below.

**Comment by omichel** [comment]
> In most source code example (and shells), we add one space to indent the code. This is not good. We should remove this space and add some padding to the corresponding <div> (this is related with my previous comment).

Also you didn't address this comment. In the source of our md files, we are systematically adding one space on the left hand side when writing C source code of shell source code. We should remove this and have the CSS add some padding or margin.

**Comment by fabienrohrer** [comment]
I'm sorry, but I'm still not sure to understand well.

Do you speak about these 2 spaces?

#### 1

```markdown
>```c
> #include <webots/robot.h>
 ^ HERE
```

#### 2

(in red)

capture d ecran 2016-07-04 a 16 05 01

**Comment by fabienrohrer** [comment]
(I have a complete control on the red padding of the °2 point: I currently removed it completely.)

**Comment by omichel** [comment]
Yes, the indents you removed are are good thing.

**Comment by fabienrohrer** [comment]
Ok, very well. So it seems completed.

**Comment by fabienrohrer** [comment]
👍

**Comment by omichel** [comment]
Ok, so now the blocks of code is indented the same way as the node definitions in 
https://www.cyberbotics.com/doc/reference/speaker?version=fix-highlight-in-quotes
However, I feel like we should add some small margins to make it looks better. I will try something and let you check it, so that you better understand what I mean.

**Comment by omichel** [comment]
Here is what I meant (see my last commit).

:+1:

**Comment by fabienrohrer** [comment]
Ok perfect :-)

👍

**Pull request merged**
