### PR TITLE
extend doc to include frustum culling option

### PR DESCRIPTION
**Pull request by tn12787**

### CODE REVIEW

**Comment by tn12787** [comment]
👍

**Comment by tn12787** [comment]
👎 following main PR comments

**Comment by stefaniapedrazzi** [comment]
Related with #6076.
Note that you change the window title and this image is displayed in the web-scene page and not web-animation one.

**Comment by tn12787** [comment]
I'm replacing this screenshot with an "Export HTML5 Model" dialog instead.

**Comment by tn12787** [comment]
capture


The dialog screenshot on `develop` doesn't seem to be centered correctly. I'm fixing this in this PR.

**Comment by tn12787** [comment]
👍

**Pull request merged**
