### PR TITLE
Merge master to webots r2018a revision 2

### PR DESCRIPTION
**Pull request by fabienrohrer**
Ditto

### CODE REVIEW

**Comment by fabienrohrer** [comment]
👍

**Comment by fabienrohrer** [comment]
👍 (more commits to merge)

**Comment by DavidMansolino** [comment]
What were the conflicting files?

**Comment by fabienrohrer** [comment]
Sorry, I forgot to mention that: there was no conflicts at all.

**Comment by fabienrohrer** [comment]
I think it's no more possible to create mergeable PRs without branches (the "Update" button of github prohibits to merge the PR in this case).

**Comment by DavidMansolino** [comment]
Argh... this button is really a pain!

**Pull request merged**
