### PR TITLE
Use querySelector API where possible

### PR DESCRIPTION
**Pull request by tn12787**
ditto.

### CODE REVIEW

**Comment by tn12787** [comment]
:+1:

**Comment by tn12787** [comment]
:-1:

**Comment by tn12787** [comment]
preview https://www.cyberbotics.com/doc/blog/Webots-2018-a-release?version=cleanup-use-query-selectors

**Comment by tn12787** [comment]
👍

**Comment by omichel** [comment]
:eyes:

**Comment by tn12787** [comment]
👍

**Comment by omichel** [comment]
The scroll to anchor still has problems...

**Comment by tn12787** [comment]
better preview: (the blog doesn't have the contribution banner) https://www.cyberbotics.com/doc/reference/appearance?version=cleanup-use-query-selectors

**Comment by tn12787** [comment]
👍

**Pull request merged**
