### PR TITLE
Merge master into webots8.5.5

### PR DESCRIPTION
**Pull request by DavidMansolino**
ditto

### CODE REVIEW

**Comment by DavidMansolino** [comment]
:+1:

**Comment by stefaniapedrazzi** [comment]
This is wrong, because there is an intermediate branch to update:
master -> webots8.5.5 -> develop

The master is the one used by the website.
webots8.5.5 is the branch matching the master@webots branch.

**Comment by DavidMansolino** [comment]
Ok, so if I understood correctly these are the steps I should do:
  1. Merge master into webots8.5.5
  2. Update master@webots to points to webots8.5.5
  3. Merge webots8.5.5 into develop
  4. Update develop@webots to points to develop

Is this correct?

**Comment by stefaniapedrazzi** [comment]
Yes.
(I think we often skip step 2 and 4, but it would be good to apply them)

**Comment by DavidMansolino** [comment]
:+1: 

Thank you for the explanation.

**Pull request merged**
