### PR TITLE
Improve API headers

### LINKED ISSUE #591: Language APIs docs are not user friendly
The description of API functions in different languages is not easy to understand for new users. We should setup a new system to improve that.

For example, each function could be presented under a tab row that would allow the user to select among C, C++, Python, Java, MATLAB, ROS. The tab selection of the user should be stored (in the browser cookie for example) so that it becomes the default tab selected.

I believe this could be handled by some Javascript code that will manage the tabs, perform some search and replace in the text (to replace a C function name by a C++ method name) and display the needed text sections.

### PR DESCRIPTION
**Pull request by fabienrohrer**
Partially fix #591 (in prevision to do better later)

Aim: see the API functions in the page index.

Before: https://www.cyberbotics.com/doc/reference/camera
After: https://www.cyberbotics.com/doc/reference/camera?version=enhancement-api-headers

### CODE REVIEW

**Comment by fabienrohrer** [comment]
Can I scale with this solution?

**Comment by omichel** [comment]
Yes, but it doesn't look super nice when the function names are on two lines (the indentation of the second line indentation looks bad).

**Comment by omichel** [comment]
Yes, it looks much better to me. Thank you.

**Comment by fabienrohrer** [comment]
Ok, I will scale with this.

**Comment by fabienrohrer** [comment]
I still improved the API. Mainly, the OO links are now displayed as tags:

capture d ecran 2018-05-16 a 12 10 03

**Comment by fabienrohrer** [comment]
👍

**Comment by fabienrohrer** [comment]
👍

**Pull request merged**
