### PR TITLE
Fix Code Highlighting

### PR DESCRIPTION
**Pull request by tn12787**
This PR fixes an issue with code highlighting from #673, simplifying the selector process for getting code blocks.

### CODE REVIEW

**Comment by tn12787** [comment]
preview: https://www.cyberbotics.com/doc/reference/brake?version=fix-broken-code-highlighting

**Comment by tn12787** [comment]
👍

**Comment by fabienrohrer** [comment]
👀

**Comment by fabienrohrer** [comment]
Could you explain why you changed "c++" to "cpp". A priori it seems less readable to me.

**Comment by tn12787** [comment]
`.c++` is not a valid CSS selector (you can't use characters like `+`) whereas they can be used in HTML5 attributes. If we use `getElementsByClassName` we can use a selector like `.c++` but using query selector this does not work so we must use `.cpp` instead.

**Pull request merged**
