### PR TITLE
Webots 8.5.3

### PR DESCRIPTION
**Pull request by fabienrohrer**
To be merged when releasing Webots 8.5.3.

### CODE REVIEW

**Comment by fabienrohrer** [comment]
I added this into our release procedure: https://github.com/omichel/webots/wiki/Release-procedure/_compare/6042ec4d77df0aefed88b78569498637a10de189

**Comment by fabienrohrer** [comment]
I think we can now merge this PR in master.

👍

**Comment by omichel** [comment]
No, I would merge it only after we released Webots 8.5.3. Meanwhile the webots master should point to this branch instead of the webots-doc master branch.

**Comment by fabienrohrer** [comment]
Ok, so we have to be carful about this when releasing :-(

**Comment by fabienrohrer** [comment]
and we have to merge master here, which is not the case

**Comment by omichel** [comment]
(we need to merge it into the master now that Webots 8.5.3 is released)
👍

**Pull request merged**
