### PR TITLE
Add Travis status in the README

### PR DESCRIPTION
**Pull request by fabienrohrer**
cf. http://stackoverflow.com/questions/19810386/showing-travis-build-status-in-github-repo

### CODE REVIEW

**Comment by fabienrohrer** [comment]
Result:
https://github.com/omichel/webots-doc/blob/enhancement-travis-status/README.md

**Comment by fabienrohrer** [comment]
It is marked as unknown, probably because the last commit pushed after a PR is not tested because the "Build pushes" settings is disabled.

In this case, Olivier, could you invert "Build pushes" and "Build pull requests"?
Note these options are poorly documented:
https://blog.travis-ci.com/2014-03-05-repository-settings/

**Comment by omichel** [comment]
Done.

**Comment by fabienrohrer** [comment]
The new settings seems to work much better. All the pushes are tested, including branch merge, PR creation, and new commits.
https://github.com/omichel/webots-doc/pull/101

**Comment by fabienrohrer** [comment]
👍

**Comment by fabienrohrer** [comment]
In PR #90, the 2 last commits have not been tested (after disabling the "Build pull requests" setting). So it seems that these both settings have their meaning. @omichel Could you enable them both (default value)?

**Comment by omichel** [comment]
Done.

**Comment by fabienrohrer** [comment]
Ok, I think the status should work just after the merge of this PR.

**Comment by fabienrohrer** [comment]
👍

**Comment by omichel** [comment]
:+1:

**Comment by omichel** [comment]
It seems to work.

**Comment by fabienrohrer** [comment]
yep :-P

**Pull request merged**
