### PR TITLE
Update webots-doc.css

### PR DESCRIPTION
**Pull request by omichel**
That increases readability of code and makes the code font look at a similar size to the normal text font (already uploaded on cyberbotics' web site for testing).

### CODE REVIEW

**Comment by omichel** [comment]
:+1:

**Comment by DavidMansolino** [comment]
:+1:

**Comment by fabienrohrer** [comment]
maybe that increasing the vertical padding and margin of the code blocks would also help, like there:
https://developer.mozilla.org/fr/docs/Web/HTML/Element/a

Currently my feeling is that some spaces are missing, rendering the visual "congested".

**Comment by omichel** [comment]
I agree. I will try to improve that.

**Comment by omichel** [comment]
:+1:

**Comment by omichel** [comment]
:+1:

**Comment by fabienrohrer** [comment]
👍  The result is very nice!

**Pull request merged**
