### PR TITLE
Enhancement of the index location and look

### PR DESCRIPTION
**Pull request by fabienrohrer**
- [x] Change the index rules to be created just before the second title.
- [x] Improve the index look.

Some previews:

- https://www.cyberbotics.com/doc/guide/cpp-java-python?version=enhancement-index
- https://www.cyberbotics.com/doc/guide/robotis-op2?version=enhancement-index
- https://www.cyberbotics.com/doc/reference/robot?version=enhancement-index

### CODE REVIEW

**Comment by fabienrohrer** [comment]
@tn12787 I'm done with the backend :-)

**Comment by omichel** [comment]
It doesn't work: the index is after the first title, not before the second one...

**Comment by fabienrohrer** [comment]
@omichel Could you refresh your cache? I think it's working.

**Comment by tn12787** [comment]
It's working fine for me! I just pushed better CSS. The change is very slight but improves the legibility of the index considerably, in my opinion.

**Comment by omichel** [comment]
Yes, thank you. After refreshing the cache, it works.

**Comment by tn12787** [comment]
:+1:

**Pull request merged**
