### PR TITLE
Add description of OpenGL line width preferences option

### PR DESCRIPTION
**Pull request by stefaniapedrazzi**
Related to https://github.com/omichel/webots/pull/6213.

### CODE REVIEW

**Comment by stefaniapedrazzi** [comment]
:+1:

**Comment by tn12787** [comment]
Does this parameter also affect the lines drawn in the translate/rotate handles?

**Comment by stefaniapedrazzi** [comment]
Yes, they are the coordinate system lines.

**Comment by tn12787** [comment]
OK. I think it would be good to explicitly refer to these (along with the force and torque handles).

**Comment by stefaniapedrazzi** [comment]
Ok. I think that they are already referred as coordinate system because this is what they are representing and having a too long and too specific list is just worst.
But I can add them.

**Comment by stefaniapedrazzi** [comment]
:+1:

**Pull request merged**
