### PR TITLE
Updated documentation to describe Python 3 support

### PR DESCRIPTION
**Pull request by omichel**
Documents https://github.com/omichel/webots/pull/6419.

### CODE REVIEW

**Comment by omichel** [comment]
👍

**Comment by omichel** [comment]
👍

**Comment by fabienrohrer** [comment]
👀

**Comment by omichel** [comment]
I am closing this PR and re-opening a correct one aiming at the develop branch.

**Comment by fabienrohrer** [comment]
perfect, thank you

**Pull request closed without merging**
