### PR TITLE
Use jQuery Layout UI to create a resizable/closable menu at west

### PR DESCRIPTION
**Pull request by fabienrohrer**
Ditto

### CODE REVIEW

**Comment by fabienrohrer** [comment]
The first results are very encouraging: it simplifies the layout code drastically and is very smooth to use.

Example:

- default menu width:

capture d ecran 2016-06-28 a 17 56 36

- big menu width:

capture d ecran 2016-06-28 a 17 56 47

- closed menu:

capture d ecran 2016-06-28 a 17 56 51

**Comment by fabienrohrer** [comment]
@omichel Could I ask you to try apply this on the Cyberbotics website?

In theory, this should be straight forward:
- Integration of #90 should be done before.
- the "jQuery layout UI" library is applied at the `webots-doc` div level only, as in the layout container sample:
    - http://layout.jquery-dev.com/demos.cfm (container demo)
    - http://layout.jquery-dev.com/demos/container.html

**Comment by fabienrohrer** [comment]
👍

**Comment by stefaniapedrazzi** [comment]
How do you close the menu? simply dragging on the left?
I cannot close it in the dock widget.. but the resizing works fine.

**Comment by fabienrohrer** [comment]
By double-clicking on the drag handle..
I tried quickly to do the same way we do in Webots, but didn't find a solution yet. I will investigate more right now.

**Comment by stefaniapedrazzi** [comment]
Ok, thank you. With double click it works fine.
But the area where you have to double click is quite small.

Some subsection title seems to be cut, in this case we should re-add the horizontal scrollbar:
dock_widget

**Comment by stefaniapedrazzi** [comment]
Maybe we could also further reduce the minimum size.
Ideally not having any minimum size would probably be better.

**Comment by fabienrohrer** [comment]
Your propositions are good to me.

If I reduce the minimum size to 0, it acts like a second and more intuitive way to close the menu.
I have issues to set the horizontal scroll bar under some minimum width, but this is certainly possible, I'm investigating this.

**Comment by stefaniapedrazzi** [comment]
By the way a single click on the handle (highlighted in yellow) works as well to hide the left menu.

**Comment by fabienrohrer** [comment]
thank you for the tip

**Comment by omichel** [comment]
I just tested it on cyberbotics's web site and it doesn't work (nothing is actually displayed).
You can test also by yourself as I put the interesting files (`webots-doc.css` `doc.php` and `viewer.js`) on the FTP server of Cyberbotics in `repository/www/wwi/8.5`.

**Comment by fabienrohrer** [comment]
Ok, thank you. I didn't know I had access to `doc.php`. So I can go on with this if you would like.

**Comment by omichel** [comment]
Yes, please.

**Comment by fabienrohrer** [comment]
@stefaniapedrazzi I implemented your propositions and it seems to be simpler to use now.

**Comment by fabienrohrer** [comment]
On the Cyberbotics website, there are height issues similar to the ones we get with iframes.

**Comment by omichel** [comment]
The doc on the web site is currently broken: https://www.cyberbotics.com/doc/guide/index
Nothing is displayed any more...

**Comment by fabienrohrer** [comment]
Yes, because I'm currently working on this. I will restore this, and try to work locally rather.

**Comment by omichel** [comment]
Ok, thank you.

**Comment by fabienrohrer** [comment]
The previous state is restored.

**Comment by fabienrohrer** [comment]
I have a working example here:
https://github.com/omichel/webots-doc/blob/enhancement-resizable-menu/test.html

Remains to apply it ;-)

**Comment by fabienrohrer** [comment]
The last results I get with this implementation are not satisfying. Probably due to the dynamic load, the height of the container is difficult to compute, and I ask myself if the overall is the good approach.

**Comment by fabienrohrer** [comment]
Solution in #116 is preferable to this solution.

**Pull request closed without merging**
