### PR TITLE
Cleanup Node List

### PR DESCRIPTION
**Pull request by DavidMansolino**
Remove unsupported/experimental nodes from the list (related to omichel/webots#7420, dual PR: omichel/webots#7451).

### CODE REVIEW

**Comment by DavidMansolino** [comment]
👍

**Comment by stefaniapedrazzi** [comment]
:eyes:

**Comment by DavidMansolino** [comment]
👍

**Comment by DavidMansolino** [comment]
👍

**Comment by stefaniapedrazzi** [comment]
:eyes:

**Comment by DavidMansolino** [comment]
> I also fixed the alphabetical order of LED/LIDAR in C++/Java/Python.

Thank you.

**Pull request merged**
