### PR TITLE
Renamed books index page

### PR DESCRIPTION
**Pull request by omichel**
:+1:

### CODE REVIEW

**Comment by fabienrohrer** [comment]
`viewer.js` is also refering several time book.md, at least there:
https://github.com/omichel/webots-doc/blob/master/js/viewer.js#L529
https://github.com/omichel/webots-doc/blob/master/js/viewer.js#L479

**Comment by omichel** [comment]
Ok, I am fixing it...

**Comment by omichel** [comment]
:+1:

**Comment by fabienrohrer** [comment]
👍

**Pull request merged**
