### PR TITLE
Fix OSM importer dependencies on Ubuntu 14.04

### PR DESCRIPTION
**Pull request by DavidMansolino**
Fix omichel/webots#6540

### CODE REVIEW

**Comment by DavidMansolino** [comment]
:+1:

**Comment by stefaniapedrazzi** [comment]
:eyes:

**Comment by stefaniapedrazzi** [comment]
On Ubuntu 14.04 it works fine but there is the same issue also on Ubuntu 16.04.

It would be better to test the OSM importer also on macOS.

**Comment by DavidMansolino** [comment]
Actually `webcolors` is a new dependency introduced in omichel/webots#5542 and it should therefore be installed on all the platforms.

**Comment by DavidMansolino** [comment]
:+1:

**Pull request merged**
