### PR TITLE
Fix macOS font

### LINKED ISSUE #402: TTF fonts on mac
In https://github.com/omichel/webots/pull/5667 I had to workaround a bug in QtWebKit about the support of CSS font-face.

It could be good to check if Qt > 5.9 solves this.

### PR DESCRIPTION
**Pull request by fabienrohrer**
Attempt to fix #402

- Prefer TTF font rather than WOFF format for the Raleway font (better support in QWebKit).
- Removed custom macOS CSS.

### CODE REVIEW

**Comment by fabienrohrer** [comment]
From https://stackoverflow.com/a/11857826/2210777:

> QWebView doesn't like WOFF fonts.


- state before (wrong font)

capture d ecran 2017-11-14 a 17 32 02


- forcing WOFF font (buggy font)

capture d ecran 2017-11-14 a 17 31 12

- with the TTF font:
capture d ecran 2017-11-14 a 17 30 22

**Comment by fabienrohrer** [comment]
I think I will even go further and drop this WOFF font (rather using it as a fallback).

**Comment by fabienrohrer** [comment]
Seems to work as expected on Windows:

capture d ecran 2017-11-14 a 18 07 02

**Comment by fabienrohrer** [comment]
👍

**Comment by omichel** [comment]
:eyes:

**Pull request merged**
