### PR TITLE
Fix rendering issue in the Raleway font at least on macOS local documentation.

### PR DESCRIPTION
**Pull request by fabienrohrer**
https://github.com/omichel/webots/issues/5647

Could I ask for tests on linux and windows?

### CODE REVIEW

**Comment by stefaniapedrazzi** [comment]
Yes, I can test on Linux.

**Comment by stefaniapedrazzi** [comment]
I confirm it works correctly on linux.

**Comment by omichel** [comment]
I am testing on Windows...

**Comment by omichel** [comment]
Yes, it works on Windows as well.

**Comment by fabienrohrer** [comment]
Ok, then it seems to be the good solution, thank you for the tests.

**Comment by fabienrohrer** [comment]
👍

**Pull request merged**
