### PR TITLE
Fix Vertical Figure > Img Scrollbar

### LINKED ISSUE #787: Unneded vertical scrollbar for images
When opening the offline User Guide in Webots, I see a vertical scrollbar for the image.
This is not always visible but depends on the width of the documentation.

offline_guide

### PR DESCRIPTION
**Pull request by tn12787**
fix #787.

### CODE REVIEW

**Comment by tn12787** [comment]
Since this bug is only reproducible embedded in Webots, I'm not posting a preview link.

**Comment by tn12787** [comment]
:+1:

**Comment by stefaniapedrazzi** [comment]
:eyes:

**Comment by stefaniapedrazzi** [comment]
Did you check why this overflow property was introduced and that it still works correctly?

**Comment by tn12787** [comment]
Yes, It was introduced by @fabienrohrer and I several months ago to remove some horizontal scrollbars on figures. It wasn't a very good solution as it only took care of the x direction and used "auto" so was up to the User Agent Stylesheet to do whatever it wanted. We always want figures to be completely visible and we have responsive widths set up such that we should never need a scrollbar (just like the unnecessary one here), so it is safe to disable scrolling on these figures.

**Comment by stefaniapedrazzi** [comment]
Ok.
As far as I could see this was introduced by @DavidMansolino  in the charts feature PR.
But charts doesn't seem to be displayed correctly in any case.

**Comment by DavidMansolino** [comment]
@tn12787 are you sure this doesn't break the chart?
It seems the horizontal scrollbar is not working on chart on the online doc now...

**Pull request merged**
