### PR TITLE
Fix anchor scroll position (re-open)

### PR DESCRIPTION
**Pull request by omichel**
Re-open #47 which was closed by mistake.

### CODE REVIEW

**Comment by fabienrohrer** [comment]
Reading the scrollIntoView doc (https://developer.mozilla.org/fr/docs/Web/API/Element/scrollIntoView) we can maybe accept that an arbitrary offset is setup, because the doc is suggesting this..

**Comment by omichel** [comment]
I don't see anything in the doc that would suggest this...

**Comment by omichel** [comment]
I tried a simple example that uses our CSS and doesn't have this 180 pixel offset problem.
[test.zip](https://github.com/omichel/webots-doc/files/248368/test.zip)

**Comment by fabienrohrer** [comment]
> I don't see anything in the doc that would suggest this...

They say:

> L'élément peut ne pas être aligné complètement avec le haut ou le bas, selon la disposition des autres éléments.

Meaning for me that depending on the other elements, an arbitrary offset is to be expected :-/

**Comment by omichel** [comment]
For me that explains that is the page is too short, the anchor is not aligned with the top of the page. If you take my simple example, it works fine without this 180 pixel offset. I will try to investigate what are the differences between my test example and our dynamically generated pages...

**Comment by omichel** [comment]
I really don't understand where does this offset come from... @fabienrohrer, when you originally developed the `viewer.js`, I guess the anchors were working with the exact vertical position without any vertical offset, right?

**Comment by fabienrohrer** [comment]
Yes, I think so, but I don't know when we introduced this.

**Comment by omichel** [comment]
Ok, I am giving up on this, given that it affects only the local version of the doc which is going to be discontinued soon (when we will have the embedded doc viewer in Webots).

:+1:

**Comment by fabienrohrer** [comment]
👍  (no problem)

**Pull request merged**
