### PR TITLE
Improve DOM hierarchy

### PR DESCRIPTION
**Pull request by tn12787**
This PR improves our doc's DOM arborescence.

This branch unifies the `#title` and `#view` `<div>`s under one comment `#content` container, which isn't the main page container. This allows us to apply the visual changes from @fabienrohrer's branch `enhancement-doc-readability` branch. The visual change has been applied in this branch.

### CODE REVIEW

**Comment by tn12787** [comment]
I have for the purposes of testing enacted this change in Javascript. So, I would appreciate an appearance-based first review. (I will have to change doc.php and deploy it to the `ftp` later, so it makes sense to make those changes after the appearance is accepted.)

**Comment by tn12787** [comment]
[Test page](https://www.cyberbotics.com/doc/reference/utility-functions?version=enhancment-improve-DOM-layout)

👍 (for appearance)

**Comment by omichel** [comment]
It looks good to me.

**Comment by fabienrohrer** [comment]
This is the working version of #573 :-D thank you

**Pull request merged**
