### PR TITLE
X3Dom view of robots

### PR DESCRIPTION
**Pull request by fabienrohrer**
Preview: https://www.cyberbotics.com/doc/guide/nao?version=feature-x3d-robots

- [ ] Embed X3D scenes in robot pages.
- [ ] Add a fallback to an image.
- [ ] List the robot devices (types, names, links)
- [ ] Allow to move the motors at least

### CODE REVIEW

**Comment by fabienrohrer** [comment]
Current state: I can embed Webots viewer and extract the device list (except the motors):

https://www.youtube.com/watch?v=YcpCtaZeixc

**Comment by fabienrohrer** [comment]
I integrated better the device list. When a device is selected, a billboard shows the relative center of the device and the led are colored.

[IMAGE ALT TEXT HERE](https://www.youtube.com/watch?v=Tvb5MQJQJmc)

I think I won't implement much more features for a first version.

Remains to fix bugs, simplify the mechanism, integrate better the mechanism (probably as a showdown extension) and scale to all the other robots.

**Comment by omichel** [comment]
It looks very nice! I would nevertheless suggest a new feature 😉: a "reset viewpoint" button that would reset the viewpoint to its original position/orientation as I fear some users will quickly get lost in 3D space.

**Comment by fabienrohrer** [comment]
Replaced by https://github.com/omichel/webots-doc/pull/800 (master)

**Pull request closed without merging**
