### PR TITLE
Documented Visual Studio Wizard

### PR DESCRIPTION
**Pull request by omichel**
Dual PR: https://github.com/omichel/webots/pull/7428
Preview: https://www.cyberbotics.com/doc/guide/using-visual-studio-with-webots?version=feature-visual-studio-wizard

### CODE REVIEW

**Comment by omichel** [comment]
👍

**Comment by stefaniapedrazzi** [comment]
:eyes:

**Comment by omichel** [comment]
I fixed the reference manual, but not the automobile manual where I believe it is correct to refer to Visual C++ instead of Visual Studio.

**Comment by omichel** [comment]
👍

**Pull request merged**
