### PR TITLE
Feature PROTO doc Generator

### PR DESCRIPTION
**Pull request by DavidMansolino**
Preview:
https://www.cyberbotics.com/doc/guide/objects?version=feature-proto-doc-generator
https://www.cyberbotics.com/doc/guide/object-road?version=feature-proto-doc-generator
https://www.cyberbotics.com/doc/guide/object-factory?version=feature-proto-doc-generator

https://www.cyberbotics.com/doc/automobile/menu?version=feature-proto-doc-generator

Dual PR: omichel/webots#7061

Any preliminary comments are welcome (not on the content of course as this should be improved in the PROTO files directly).

For now I am using an inclusive list of PROTO to test, but for the final version I plan to transform this into an exclusive list instead in order to not forget any future PROTO files.

Tasks:
  - [x]  Skip hidden and deprecated PROTOs
  - [x] Fix menu item order.
  - [x] Fix empty image.
  - [x] Fix image transparent.
  - [x] Fix detection of description end.
  - [x] Escape problematic caracters.
  - [x] Remove automobile objects.

### CODE REVIEW

**Comment by omichel** [comment]
I would not use "Note:" to specify the license and location of the file. Not sure what's the best for that, maybe a simple sentence or a table? Also, when the license is not specified, I would mention it explicitly, e.g., "no license specified", or even better I would break the script with an error, as I believe it is important to specify the license in all the PROTO files.

**Comment by DavidMansolino** [comment]
I think I am starting to have something functional.
Any preliminary comment is welcome (not on the text as I am still fixing this directly in the PROTO files): https://www.cyberbotics.com/doc/guide/objects?version=feature-proto-doc-generator

**Comment by DavidMansolino** [comment]
👍   Please do comment about the text content directly in omichel/webots#7061

**Comment by DavidMansolino** [comment]
👎  (I need to do some update after merge with master).

**Comment by DavidMansolino** [comment]
👍

**Comment by omichel** [comment]
The translation, rotation and name fields are not described for object PROTO nodes. We should not add them in the robot PROTO nodes. Also, I am wondering whether it is good or not to repeat all the Robot fields (inherited from Robot). That is very redundant...

**Comment by DavidMansolino** [comment]
👍

**Comment by DavidMansolino** [comment]
(text will be regenerated once omichel/webots#7061 is merged)

**Comment by DavidMansolino** [comment]
Now that omichel/webots#7061 has been approved I have regenerated the doc.

**Comment by DavidMansolino** [comment]
:+1:

**Comment by omichel** [comment]
:eyes:

**Pull request merged**
