### PR TITLE
Regenerate Objects Doc for develop

### PR DESCRIPTION
**Pull request by DavidMansolino**
https://www.cyberbotics.com/doc/guide/object-buildings?version=regenerate-objects-doc
https://www.cyberbotics.com/doc/guide/object-street-furniture?version=regenerate-objects-doc
https://www.cyberbotics.com/doc/guide/object-garden?version=regenerate-objects-doc

### CODE REVIEW

**Comment by omichel** [comment]
The SimpleBuilding also has field descriptions in the PROTO description part. That should be moved to the corresponding field description.

**Comment by omichel** [comment]
In the PicketFence segment description, it would be more interesting to have the width of a segment rather than its height (length)...

**Comment by DavidMansolino** [comment]
> The question mark on the random building icon is not very much visible. It would be more visible in white or on the red roof.

I prefer to keep it on the wall because it is the wall appearance that is random, but I will but it in white.

**Comment by DavidMansolino** [comment]
> The SimpleBuilding also has field descriptions in the PROTO description part. That should be moved to the corresponding field description.

This last issue will be fixed once we have implemented omichel/webots#7158.


👍

**Pull request merged**
