### PR TITLE
Fix Travis issues

### PR DESCRIPTION
**Pull request by fabienrohrer**
Ditto

### CODE REVIEW

**Comment by fabienrohrer** [comment]
I didn't understood well the issue yet, but it's like is sometimes, the travis server fails to reach the Cyberbotics server:

`urllib2.URLError: <urlopen error ('_ssl.c:565: The handshake operation timed out',)>`

In the last test, one test passed, and the other not, meaning that the mechanism is well written.
Maybe it's due to a temporary internet "global" issue, I don't know where the Travis server is located.

**Comment by fabienrohrer** [comment]
It's worth to try tomorrow.

**Comment by fabienrohrer** [comment]
👍 
Hum, not very convinced, but adding a multiple trial on the urllib urlopen and read is solving the issue. I don't have better idea for now.

**Comment by omichel** [comment]
:+1: That seems to be the best approach. The problem obviously lies on Travis side, not on our side. Maybe we should report it to Travis.

**Pull request merged**
