### PR TITLE
Fix copy of the showdown youtube extension

### PR DESCRIPTION
**Pull request by fabienrohrer**
Causing failure in the local doc:

capture d ecran 2017-09-07 a 15 39 06

### CODE REVIEW

**Comment by fabienrohrer** [comment]
(to be pushed to the webots8.6.1 branch later)

**Comment by fabienrohrer** [comment]
👍

**Comment by stefaniapedrazzi** [comment]
Do you know why it is working on the development system even if I don't have the youtube JS?

**Comment by stefaniapedrazzi** [comment]
Note that you merged in the wrong PR, should be webots8.6.1.

**Comment by fabienrohrer** [comment]
> Do you know why it is working on the development system even if I don't have the youtube JS?

On my developpement system, it's not working.

> Note that you merged in the wrong PR, should be webots8.6.1.

No, this is correct, the youtube tag is present on master.

**Comment by stefaniapedrazzi** [comment]
Strange on my development system the offline documentation works and I don't have this file.

**Comment by fabienrohrer** [comment]
Could it be cached?

If you want to check this, you need to uncomment QWebInspector code in WbDocumentation.cpp, and investigate how the showdown-youtube.js is loaded from the inspector.

**Comment by stefaniapedrazzi** [comment]
If I will have the time I will check.

robotbenchmark have the exact same issue.

**Comment by fabienrohrer** [comment]
On the system failing, the `showdown-youtube.js` failure cause the page to stop loading. Maybe on your system, for some reason (debug mode?) this error is dealt as a warning. There so, the only way to tell is to see what the inspector is telling.

**Pull request merged**
