### PR TITLE
Attempt to increase doc readability

### PR DESCRIPTION
**Pull request by fabienrohrer**
Aim: add a max-width for the content display, in order to increase readability.

Example: https://www.cyberbotics.com/doc/guide/webots-devices?version=enhancement-doc-readability

### CODE REVIEW

**Comment by fabienrohrer** [comment]
@all I think this modification is slightly increasing the doc readability (in full screen - otherwise it is the same). Having marges at left and right is reducing the extremely long sentences. What do you think?

**Comment by tn12787** [comment]
I think this is much better! Make sure the max-width is relative to the container width for responsivity reasons, however. Doing this also implies you should add a min-width so the doc isn't unreadable on small screens.

**Comment by omichel** [comment]
It looks good to me.

I am wondering if the left and right margin (when going above the max-width) shouldn't be displayed as a grey background. That could look even nicer.

**Comment by stefaniapedrazzi** [comment]
I think both have advantages and drawbacks.
About the readability, it is maybe slightly better.
But personally I don't like very much these big white margins that are now displayed on big window size and we loose space and we have to scroll more.
in any case any of the two version is good for me.

But in this page, the final note is not completely visible:
https://www.cyberbotics.com/doc/guide/controller-programming?version=enhancement-doc-readability

**Comment by fabienrohrer** [comment]
> I think this is much better! Make sure the max-width is relative to the container width for responsivity reasons, however. Doing this also implies you should add a min-width so the doc isn't unreadable on small screens.

I will give a try, but I'm not sure it's doable simply. Adding a min-width is 


> I am wondering if the left and right margin (when going above the max-width) shouldn't be displayed as a grey background. That could look even nicer.

I can also give a try.

> I think both have advantages and drawbacks.
About the readability, it is maybe slightly better.
But personally I don't like very much these big white margins that are now displayed on big window size and we loose space and we have to scroll more.
in any case any of the two version is good for me.

Ok. Readability is obviously subjective, I'm also not sure yet at 100% it's better.

> But in this page, the final note is not completely visible:
https://www.cyberbotics.com/doc/guide/controller-programming?version=enhancement-doc-readability

This should be fixed in my last commit.

**Comment by stefaniapedrazzi** [comment]
> This should be fixed in my last commit.

Yes, it is fixed now. Maybe it took some time to be available.

**Comment by fabienrohrer** [comment]
rawgit always takes few minutes to be refreshed :-( It's annoying.

**Comment by omichel** [comment]
We could implement our own version of rawgit... But I am not sure if the lag is in rawgit or in raw.githubusercontent.com...

**Comment by fabienrohrer** [comment]
The doc layout is not logically split, causing several issues. I will try to fix this here.

**Comment by fabienrohrer** [comment]
I need to think about this. I'm stopping this for now.

**Comment by omichel** [comment]
Shall we close this one?

**Comment by fabienrohrer** [comment]
Yes, thank you.

**Pull request closed without merging**
