### PR TITLE
Document the robot PROTO nodes and their fields

### PR DESCRIPTION
**Pull request by fabienrohrer**
Extract robot PROTO fields and add them in the documentation.

Constraint: be coherent with https://github.com/omichel/webots-doc/pull/725

Preview: https://www.cyberbotics.com/doc/guide/robots?version=enhancement-document-robot-fields

### CODE REVIEW

**Comment by fabienrohrer** [comment]
@DavidMansolino @omichel Is it ok to scale with this?

**Comment by omichel** [comment]
Yes, that's fine for me (except that the qrio.wbt is not related with the sojourner).

**Comment by fabienrohrer** [comment]
> except that the qrio.wbt is not related with the sojourner

Sorry but I don't understand this comment.

**Comment by fabienrohrer** [comment]
oh I see, this title is wrong: https://www.cyberbotics.com/doc/guide/sojourner#qrio-wbt

**Comment by DavidMansolino** [comment]
That's fine for me, it is now coherent with #725.

**Comment by omichel** [comment]
On the preview page, there is something wrong:
image

**Comment by DavidMansolino** [comment]
Note that I just write `Sojourner Field Summary` (without repeating the 'PROTO' keyword).

**Comment by fabienrohrer** [comment]
👍

**Comment by fabienrohrer** [comment]
👎  (tests are failing)

**Comment by fabienrohrer** [comment]
Now they are happy!

**Comment by fabienrohrer** [comment]
👍

**Comment by omichel** [comment]
The translation, rotation and name fields are not described for object PROTO nodes. We should not add them in the robot PROTO nodes. Also, I am wondering whether it is good or not to repeat all the Robot fields (inherited from Robot). That is very redundant...

**Comment by fabienrohrer** [comment]
I think that the robot pages are an entree point in the documentation for new users who are not aware of the Robot node. It's clearly redundant, but not documenting them is also not precise.

**Comment by omichel** [comment]
This is not consistent with #725 where translation, rotation and name are omitted.

**Comment by fabienrohrer** [comment]
Sure.

A solution could be to add a "Derived from Robot node" note or so, but in this case it presume the user should guess there is a link.

**Comment by DavidMansolino** [comment]
Note that in #725 a `Derived from XX.` is indeed added automatically at the end of the description.

**Comment by omichel** [comment]
Yes, that seems to be a good solution.

**Comment by fabienrohrer** [comment]
I'm still sketpical. I think that if a user search the fields in the documentation, it's precisely because he don't know from where they come from. It's only obvious for us. Moreover I don't where to stop with this: what about `controller`, `synchronisation` and even `camera_width`?

**Comment by fabienrohrer** [comment]
Just discussed with Olivier and David, and we will go on with the solution about documenting the derived node, and removing the fields used directly in the PROTO root node from the "field summary".

**Comment by fabienrohrer** [comment]
👍

**Comment by omichel** [comment]
That looks wrong:
image

**Comment by DavidMansolino** [comment]
For the BB8:

> maxVelocity: Defines the RotationalMotor fields. Note: the real robot moves at 4.9 [mph].

**Comment by DavidMansolino** [comment]
Same kind of issue of the Khepera IV

**Comment by fabienrohrer** [comment]
👍

**Pull request merged**
