### PR TITLE
Add python numpy installation instructions

### PR DESCRIPTION
**Pull request by stefaniapedrazzi**
Ditto.

### CODE REVIEW

**Comment by stefaniapedrazzi** [comment]
I checked on Ubuntu and Windows.
A priopri the macOs instruction should be fine but it is better to double check it.

:+1:

**Comment by omichel** [comment]
:eyes:

**Comment by omichel** [comment]
I am letting Fabien test on macOS.

**Comment by fabienrohrer** [comment]
👀  (macOS)

**Comment by fabienrohrer** [comment]
This modification is useless on macOS. `numpy` is a dependency of `python-opencv`. When installing `python-opencv` with `pip`, `numpy` is installed automatically:

```shell
pip uninstall opencv-python
Cannot uninstall requirement opencv-python, not installed
MacBook-Air:webots-master fabien$ pip install opencv-python --user
Collecting opencv-python
  Downloading opencv_python-3.3.0.10-cp27-cp27m-macosx_10_6_intel.macosx_10_9_intel.macosx_10_9_x86_64.macosx_10_10_intel.macosx_10_10_x86_64.whl (43.8MB)
    100% |████████████████████████████████| 43.8MB 21kB/s 
Collecting numpy>=1.11.1 (from opencv-python)
  Downloading numpy-1.13.3-cp27-cp27m-macosx_10_6_intel.macosx_10_9_intel.macosx_10_9_x86_64.macosx_10_10_intel.macosx_10_10_x86_64.whl (4.6MB)
    100% |████████████████████████████████| 4.6MB 142kB/s 
Installing collected packages: numpy, opencv-python
Successfully installed numpy-1.13.3 opencv-python-3.3.0.10
```

I'm reverting it if you don't mind.

**Comment by stefaniapedrazzi** [comment]
This is probably the same on Windows and UBuntu 16. I'm checking.

**Comment by fabienrohrer** [comment]
It sounds better as is.

**Comment by stefaniapedrazzi** [comment]
:+1: 

I removed the explicit installation of `numpy` and added an explanation why it is not needed.

**Comment by fabienrohrer** [comment]
👍  (already approved)

**Pull request merged**
